// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu3txYS9mvvbJ0TYqvlzozWEiLgDOUFuQ',
    appId: '1:749404815406:web:55a1fb0d5270e91e7f5fbf',
    messagingSenderId: '749404815406',
    projectId: 'sellx-e7377',
    authDomain: 'sellx-e7377.firebaseapp.com',
    storageBucket: 'sellx-e7377.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVJeFp9h0s67DCvBAtrJFAXcSAiERg9k',
    appId: '1:749404815406:android:84a83eeb6fb251497f5fbf',
    messagingSenderId: '749404815406',
    projectId: 'sellx-e7377',
    storageBucket: 'sellx-e7377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx5KecpIiY5dZrP6XARXePIxF0YaI9_pg',
    appId: '1:749404815406:ios:e37f175ee0aa7ddb7f5fbf',
    messagingSenderId: '749404815406',
    projectId: 'sellx-e7377',
    storageBucket: 'sellx-e7377.appspot.com',
    iosClientId:
        '749404815406-r2c6m1rs8e081grk6njq5dhtvg8mnrji.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIsellNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx5KecpIiY5dZrP6XARXePIxF0YaI9_pg',
    appId: '1:749404815406:ios:e37f175ee0aa7ddb7f5fbf',
    messagingSenderId: '749404815406',
    projectId: 'sellx-e7377',
    storageBucket: 'sellx-e7377.appspot.com',
    iosClientId:
        '749404815406-r2c6m1rs8e081grk6njq5dhtvg8mnrji.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIsellNew',
  );
}
